server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  redis:
    addr: 127.0.0.1:6379
    password: password
    dial_timeout: 1s
    read_timeout: 0.2s
    write_timeout: 0.2s
assets:
  md:
    dir: /data/doc
