// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/common/v1/command/command.proto

package command

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on ExecuteReq with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *ExecuteReq) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Command

	return nil
}

// ExecuteReqValidationError is the validation error returned by
// ExecuteReq.Validate if the designated constraints aren't met.
type ExecuteReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExecuteReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExecuteReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExecuteReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExecuteReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExecuteReqValidationError) ErrorName() string { return "ExecuteReqValidationError" }

// Error satisfies the builtin error interface
func (e ExecuteReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExecuteReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExecuteReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExecuteReqValidationError{}

// Validate checks the field values on ExecuteResp with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *ExecuteResp) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// ExecuteRespValidationError is the validation error returned by
// ExecuteResp.Validate if the designated constraints aren't met.
type ExecuteRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExecuteRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExecuteRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExecuteRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExecuteRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExecuteRespValidationError) ErrorName() string { return "ExecuteRespValidationError" }

// Error satisfies the builtin error interface
func (e ExecuteRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExecuteResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExecuteRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExecuteRespValidationError{}
