// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.11.4
// source: api/common/v1/user/user.proto

package user

import (
	reflect "reflect"
	sync "sync"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 登陆/注册 类型.
type ThirdPartType int32

const (
	ThirdPartType_LOGIN_TYPE_DEFAULT ThirdPartType = 0
	// 手机
	ThirdPartType_LOGIN_TYPE_PHONE ThirdPartType = 1
	// 邮箱
	ThirdPartType_LOGIN_TYPE_EMAIL ThirdPartType = 2
	// 微信
	ThirdPartType_LOGIN_TYPE_WECHAT ThirdPartType = 3
)

// Enum value maps for ThirdPartType.
var (
	ThirdPartType_name = map[int32]string{
		0: "LOGIN_TYPE_DEFAULT",
		1: "LOGIN_TYPE_PHONE",
		2: "LOGIN_TYPE_EMAIL",
		3: "LOGIN_TYPE_WECHAT",
	}
	ThirdPartType_value = map[string]int32{
		"LOGIN_TYPE_DEFAULT": 0,
		"LOGIN_TYPE_PHONE":   1,
		"LOGIN_TYPE_EMAIL":   2,
		"LOGIN_TYPE_WECHAT":  3,
	}
)

func (x ThirdPartType) Enum() *ThirdPartType {
	p := new(ThirdPartType)
	*p = x
	return p
}

func (x ThirdPartType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThirdPartType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_v1_user_user_proto_enumTypes[0].Descriptor()
}

func (ThirdPartType) Type() protoreflect.EnumType {
	return &file_api_common_v1_user_user_proto_enumTypes[0]
}

func (x ThirdPartType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThirdPartType.Descriptor instead.
func (ThirdPartType) EnumDescriptor() ([]byte, []int) {
	return file_api_common_v1_user_user_proto_rawDescGZIP(), []int{0}
}

// 登陆 请求.
type LoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Param:
	//	*LoginReq_UserLoginParam_
	//	*LoginReq_ThirdLoginParam_
	Param isLoginReq_Param `protobuf_oneof:"Param"`
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_common_v1_user_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_user_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_api_common_v1_user_user_proto_rawDescGZIP(), []int{0}
}

func (m *LoginReq) GetParam() isLoginReq_Param {
	if m != nil {
		return m.Param
	}
	return nil
}

func (x *LoginReq) GetUserLoginParam() *LoginReq_UserLoginParam {
	if x, ok := x.GetParam().(*LoginReq_UserLoginParam_); ok {
		return x.UserLoginParam
	}
	return nil
}

func (x *LoginReq) GetThirdLoginParam() *LoginReq_ThirdLoginParam {
	if x, ok := x.GetParam().(*LoginReq_ThirdLoginParam_); ok {
		return x.ThirdLoginParam
	}
	return nil
}

type isLoginReq_Param interface {
	isLoginReq_Param()
}

type LoginReq_UserLoginParam_ struct {
	UserLoginParam *LoginReq_UserLoginParam `protobuf:"bytes,1,opt,name=user_login_param,json=userLoginParam,proto3,oneof"`
}

type LoginReq_ThirdLoginParam_ struct {
	ThirdLoginParam *LoginReq_ThirdLoginParam `protobuf:"bytes,2,opt,name=third_login_param,json=thirdLoginParam,proto3,oneof"`
}

func (*LoginReq_UserLoginParam_) isLoginReq_Param() {}

func (*LoginReq_ThirdLoginParam_) isLoginReq_Param() {}

// 登陆 返回值.
type LoginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_common_v1_user_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_user_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_api_common_v1_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 注册 请求.
type RegisterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 类型
	ThirdPartType ThirdPartType `protobuf:"varint,1,opt,name=third_part_type,json=thirdPartType,proto3,enum=common.v1.user.ThirdPartType" json:"third_part_type,omitempty"`
	// 标识
	ThirdPartCode string `protobuf:"bytes,2,opt,name=third_part_code,json=thirdPartCode,proto3" json:"third_part_code,omitempty"`
	// 密码
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_common_v1_user_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_user_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_api_common_v1_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterReq) GetThirdPartType() ThirdPartType {
	if x != nil {
		return x.ThirdPartType
	}
	return ThirdPartType_LOGIN_TYPE_DEFAULT
}

func (x *RegisterReq) GetThirdPartCode() string {
	if x != nil {
		return x.ThirdPartCode
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 注册 返回值.
type RegisterResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户标识
	UserCode string `protobuf:"bytes,1,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_common_v1_user_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_user_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_api_common_v1_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResp) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

// 信息 请求.
type InfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户标识
	UserCode string `protobuf:"bytes,1,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
}

func (x *InfoReq) Reset() {
	*x = InfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_common_v1_user_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoReq) ProtoMessage() {}

func (x *InfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_user_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoReq.ProtoReflect.Descriptor instead.
func (*InfoReq) Descriptor() ([]byte, []int) {
	return file_api_common_v1_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *InfoReq) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

// 信息 返回值.
type InfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户标识
	UserCode string `protobuf:"bytes,1,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
	// 密码
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// 电话
	Phone string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	// 邮箱
	Email string `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	// 微信
	WechatOpenid string `protobuf:"bytes,6,opt,name=wechat_openid,json=wechatOpenid,proto3" json:"wechat_openid,omitempty"`
	// 头像
	Portrait string `protobuf:"bytes,10,opt,name=portrait,proto3" json:"portrait,omitempty"`
	// 昵称
	NickName string `protobuf:"bytes,11,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	// 性别
	Sex string `protobuf:"bytes,12,opt,name=sex,proto3" json:"sex,omitempty"`
}

func (x *InfoResp) Reset() {
	*x = InfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_common_v1_user_user_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResp) ProtoMessage() {}

func (x *InfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_user_user_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResp.ProtoReflect.Descriptor instead.
func (*InfoResp) Descriptor() ([]byte, []int) {
	return file_api_common_v1_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *InfoResp) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *InfoResp) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *InfoResp) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *InfoResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InfoResp) GetWechatOpenid() string {
	if x != nil {
		return x.WechatOpenid
	}
	return ""
}

func (x *InfoResp) GetPortrait() string {
	if x != nil {
		return x.Portrait
	}
	return ""
}

func (x *InfoResp) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *InfoResp) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

// 用户登陆
type LoginReq_UserLoginParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户Id
	UserCode string `protobuf:"bytes,1,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
}

func (x *LoginReq_UserLoginParam) Reset() {
	*x = LoginReq_UserLoginParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_common_v1_user_user_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReq_UserLoginParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq_UserLoginParam) ProtoMessage() {}

func (x *LoginReq_UserLoginParam) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_user_user_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq_UserLoginParam.ProtoReflect.Descriptor instead.
func (*LoginReq_UserLoginParam) Descriptor() ([]byte, []int) {
	return file_api_common_v1_user_user_proto_rawDescGZIP(), []int{0, 0}
}

func (x *LoginReq_UserLoginParam) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

// 第三方登陆
type LoginReq_ThirdLoginParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 类型
	ThirdPartType ThirdPartType `protobuf:"varint,1,opt,name=third_part_type,json=thirdPartType,proto3,enum=common.v1.user.ThirdPartType" json:"third_part_type,omitempty"`
	// 标识
	ThirdPartCode string `protobuf:"bytes,2,opt,name=third_part_code,json=thirdPartCode,proto3" json:"third_part_code,omitempty"`
}

func (x *LoginReq_ThirdLoginParam) Reset() {
	*x = LoginReq_ThirdLoginParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_common_v1_user_user_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReq_ThirdLoginParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq_ThirdLoginParam) ProtoMessage() {}

func (x *LoginReq_ThirdLoginParam) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_user_user_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq_ThirdLoginParam.ProtoReflect.Descriptor instead.
func (*LoginReq_ThirdLoginParam) Descriptor() ([]byte, []int) {
	return file_api_common_v1_user_user_proto_rawDescGZIP(), []int{0, 1}
}

func (x *LoginReq_ThirdLoginParam) GetThirdPartType() ThirdPartType {
	if x != nil {
		return x.ThirdPartType
	}
	return ThirdPartType_LOGIN_TYPE_DEFAULT
}

func (x *LoginReq_ThirdLoginParam) GetThirdPartCode() string {
	if x != nil {
		return x.ThirdPartCode
	}
	return ""
}

var File_api_common_v1_user_user_proto protoreflect.FileDescriptor

var file_api_common_v1_user_user_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf2, 0x02,
	0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x53, 0x0a, 0x10, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x48, 0x00, 0x52,
	0x0e, 0x75, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12,
	0x56, 0x0a, 0x11, 0x74, 0x68, 0x69, 0x72, 0x64, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x2e, 0x54, 0x68, 0x69, 0x72, 0x64, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x48, 0x00, 0x52, 0x0f, 0x74, 0x68, 0x69, 0x72, 0x64, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x2d, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x1a, 0x80, 0x01, 0x0a, 0x0f, 0x54, 0x68, 0x69, 0x72, 0x64,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x45, 0x0a, 0x0f, 0x74, 0x68,
	0x69, 0x72, 0x64, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x0d, 0x74, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x26, 0x0a, 0x0f, 0x74, 0x68, 0x69, 0x72, 0x64, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x68, 0x69, 0x72,
	0x64, 0x50, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x22, 0x21, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x98, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x45, 0x0a, 0x0f, 0x74, 0x68, 0x69, 0x72, 0x64, 0x5f, 0x70,
	0x61, 0x72, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0d, 0x74,
	0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x0f,
	0x74, 0x68, 0x69, 0x72, 0x64, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x22, 0x2b, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x26, 0x0a,
	0x07, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0xdf, 0x01, 0x0a, 0x08, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x77, 0x65, 0x63, 0x68, 0x61,
	0x74, 0x5f, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x77, 0x65, 0x63, 0x68, 0x61, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x6f, 0x72, 0x74, 0x72, 0x61, 0x69, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x6f, 0x72, 0x74, 0x72, 0x61, 0x69, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x69, 0x63, 0x6b,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63,
	0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x78, 0x2a, 0x6a, 0x0a, 0x0d, 0x54, 0x68, 0x69, 0x72, 0x64,
	0x50, 0x61, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x4c, 0x4f, 0x47, 0x49,
	0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x00,
	0x12, 0x14, 0x0a, 0x10, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50,
	0x48, 0x4f, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x4d, 0x41, 0x49, 0x4c, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11,
	0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x57, 0x45, 0x43, 0x48, 0x41,
	0x54, 0x10, 0x03, 0x32, 0xab, 0x02, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x5e, 0x0a, 0x05,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x18, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x1a,
	0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x1a, 0x22, 0x15, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x3a, 0x01, 0x2a, 0x12, 0x6a, 0x0a, 0x08,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x23, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x22, 0x18, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x3a, 0x01, 0x2a, 0x12, 0x57, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x12, 0x14, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x66,
	0x6f, 0x42, 0x1a, 0x5a, 0x18, 0x74, 0x68, 0x6f, 0x6f, 0x68, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_common_v1_user_user_proto_rawDescOnce sync.Once
	file_api_common_v1_user_user_proto_rawDescData = file_api_common_v1_user_user_proto_rawDesc
)

func file_api_common_v1_user_user_proto_rawDescGZIP() []byte {
	file_api_common_v1_user_user_proto_rawDescOnce.Do(func() {
		file_api_common_v1_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_common_v1_user_user_proto_rawDescData)
	})
	return file_api_common_v1_user_user_proto_rawDescData
}

var file_api_common_v1_user_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_common_v1_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_common_v1_user_user_proto_goTypes = []interface{}{
	(ThirdPartType)(0),               // 0: common.v1.user.ThirdPartType
	(*LoginReq)(nil),                 // 1: common.v1.user.LoginReq
	(*LoginResp)(nil),                // 2: common.v1.user.LoginResp
	(*RegisterReq)(nil),              // 3: common.v1.user.RegisterReq
	(*RegisterResp)(nil),             // 4: common.v1.user.RegisterResp
	(*InfoReq)(nil),                  // 5: common.v1.user.InfoReq
	(*InfoResp)(nil),                 // 6: common.v1.user.InfoResp
	(*LoginReq_UserLoginParam)(nil),  // 7: common.v1.user.LoginReq.UserLoginParam
	(*LoginReq_ThirdLoginParam)(nil), // 8: common.v1.user.LoginReq.ThirdLoginParam
}
var file_api_common_v1_user_user_proto_depIdxs = []int32{
	7, // 0: common.v1.user.LoginReq.user_login_param:type_name -> common.v1.user.LoginReq.UserLoginParam
	8, // 1: common.v1.user.LoginReq.third_login_param:type_name -> common.v1.user.LoginReq.ThirdLoginParam
	0, // 2: common.v1.user.RegisterReq.third_part_type:type_name -> common.v1.user.ThirdPartType
	0, // 3: common.v1.user.LoginReq.ThirdLoginParam.third_part_type:type_name -> common.v1.user.ThirdPartType
	1, // 4: common.v1.user.User.Login:input_type -> common.v1.user.LoginReq
	3, // 5: common.v1.user.User.Register:input_type -> common.v1.user.RegisterReq
	5, // 6: common.v1.user.User.Info:input_type -> common.v1.user.InfoReq
	2, // 7: common.v1.user.User.Login:output_type -> common.v1.user.LoginResp
	4, // 8: common.v1.user.User.Register:output_type -> common.v1.user.RegisterResp
	6, // 9: common.v1.user.User.Info:output_type -> common.v1.user.InfoResp
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_common_v1_user_user_proto_init() }
func file_api_common_v1_user_user_proto_init() {
	if File_api_common_v1_user_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_common_v1_user_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_common_v1_user_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_common_v1_user_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_common_v1_user_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_common_v1_user_user_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_common_v1_user_user_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_common_v1_user_user_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReq_UserLoginParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_common_v1_user_user_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReq_ThirdLoginParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_common_v1_user_user_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*LoginReq_UserLoginParam_)(nil),
		(*LoginReq_ThirdLoginParam_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_common_v1_user_user_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_common_v1_user_user_proto_goTypes,
		DependencyIndexes: file_api_common_v1_user_user_proto_depIdxs,
		EnumInfos:         file_api_common_v1_user_user_proto_enumTypes,
		MessageInfos:      file_api_common_v1_user_user_proto_msgTypes,
	}.Build()
	File_api_common_v1_user_user_proto = out.File
	file_api_common_v1_user_user_proto_rawDesc = nil
	file_api_common_v1_user_user_proto_goTypes = nil
	file_api_common_v1_user_user_proto_depIdxs = nil
}
